services:
  - type: web
    name: ambulance-tracking
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT ambulance.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "ambulance-tracking.onrender.com"
      - key: REDIS_URL
        fromService:
          type: redis
          name: ambulance-redis
          property: connectionString

databases:
  - name: ambulance-redis
    type: redis