# Generated by Django 4.2.28 on 2026-02-22 09:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "licens",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid license key (5 alphanumeric characters).",
                                regex="^[A-Z0-9]{5}$",
                            )
                        ],
                    ),
                ),
                ("current_lat", models.FloatField()),
                ("current_long", models.FloatField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("On", "Online"),
                            ("Off", "Offline"),
                            ("Busy", "En route"),
                            ("Accidents", "Accident"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
