# Generated by Django 4.2.28 on 2026-02-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="current_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="current_long",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
