# Generated by Django 4.2.28 on 2026-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_alter_driver_current_lat_alter_driver_current_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="ambulance_type",
            field=models.CharField(
                choices=[("ICU", "ICU"), ("ALS", "ALS"), ("BLS", "BLS")],
                default=2,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
