# Generated by Django 4.2.28 on 2026-02-22 09:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "hosp",
                    models.CharField(
                        choices=[("gov", "Governement"), ("pri", "Private")],
                        max_length=30,
                    ),
                ),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                blank=True,
                choices=[("Admin", "admin"), ("Driver", "driver")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phno",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("pickup_lat", models.FloatField()),
                ("pickup_long", models.FloatField()),
                ("drop_lat", models.FloatField(blank=True, null=True)),
                ("drop_long", models.FloatField(blank=True, null=True)),
                (
                    "ambulance_type",
                    models.CharField(
                        choices=[
                            ("ICU", "Advance cardiac care"),
                            ("ALS", "Advance life support"),
                            ("BLS", "Basic life support "),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hospital_prefrences",
                    models.CharField(
                        choices=[
                            ("Gov", "Governement"),
                            ("Pri", "Private"),
                            ("near", "Nearest"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("assigned", "assigned"),
                            ("in_progress", "in_progress"),
                            ("completed", "completed"),
                            ("terminated", "terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="driver.driver",
                    ),
                ),
                (
                    "assigned_hosp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.hospital",
                    ),
                ),
            ],
        ),
    ]
